structure(list(url = "https://rest.uniprot.org/uniprotkb/P60709.fasta", 
    status_code = 200L, headers = structure(list(vary = "accept,accept-encoding,x-uniprot-release,x-api-deployment-date, User-Agent, Accept-Encoding", 
        `cache-control` = "public, max-age=43200", `x-cache` = "miss cached", 
        `content-type` = "text/plain;format=fasta", `content-encoding` = "gzip", 
        `access-control-allow-credentials` = "true", `access-control-expose-headers` = "Link, X-Total-Results, X-UniProt-Release, X-UniProt-Release-Date, X-API-Deployment-Date", 
        `x-api-deployment-date` = "29-July-2026", `strict-transport-security` = "max-age=31536000; includeSubDomains", 
        date = "Tue, 11 Aug 2026 14:27:02 GMT", `access-control-max-age` = "1728000", 
        `x-uniprot-release` = "2026_02", `access-control-allow-origin` = "*", 
        `accept-ranges` = "bytes", `access-control-allow-methods` = "GET, PUT, POST, DELETE, PATCH, OPTIONS", 
        `access-control-allow-headers` = "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization", 
        `x-uniprot-release-date` = "10-June-2026", `content-length` = "0"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 301L, version = "HTTP/2", 
        headers = structure(list(`content-type` = "text/html", 
            date = "Tue, 11 Aug 2026 14:29:30 GMT", location = "https://rest.uniprot.org/uniprotkb/P60709.fasta", 
            `content-length` = "0"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/2", headers = structure(list(
        vary = "accept,accept-encoding,x-uniprot-release,x-api-deployment-date, User-Agent, Accept-Encoding", 
        `cache-control` = "public, max-age=43200", `x-cache` = "miss cached", 
        `content-type` = "text/plain;format=fasta", `content-encoding` = "gzip", 
        `access-control-allow-credentials` = "true", `access-control-expose-headers` = "Link, X-Total-Results, X-UniProt-Release, X-UniProt-Release-Date, X-API-Deployment-Date", 
        `x-api-deployment-date` = "29-July-2026", `strict-transport-security` = "max-age=31536000; includeSubDomains", 
        date = "Tue, 11 Aug 2026 14:27:02 GMT", `access-control-max-age` = "1728000", 
        `x-uniprot-release` = "2026_02", `access-control-allow-origin` = "*", 
        `accept-ranges` = "bytes", `access-control-allow-methods` = "GET, PUT, POST, DELETE, PATCH, OPTIONS", 
        `access-control-allow-headers` = "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization", 
        `x-uniprot-release-date` = "10-June-2026", `content-length` = "0"), class = c("insensitive", 
    "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = raw(0), date = structure(1786458422, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0.076068, 
    namelookup = 0.001621, connect = 0.023151, pretransfer = 0.059481, 
    starttransfer = 0.09238, total = 0.09254)), class = "response")
