structure(list(method = "POST", url = "https://rest.uniprot.org/idmapping/run", 
    status_code = 200L, headers = structure(list(vary = "accept,accept-encoding,x-uniprot-release,x-api-deployment-date", 
        vary = "User-Agent", `cache-control` = "no-cache", `content-type` = "application/json", 
        `content-encoding` = "gzip", `access-control-allow-credentials` = "true", 
        `access-control-expose-headers` = "Link, X-Total-Results, X-UniProt-Release, X-UniProt-Release-Date, X-API-Deployment-Date", 
        `x-api-deployment-date` = "11-July-2026", `strict-transport-security` = "max-age=31536000; includeSubDomains", 
        date = "Tue, 11 Aug 2026 14:21:12 GMT", `access-control-max-age` = "1728000", 
        `x-uniprot-release` = "2026_02", `access-control-allow-origin` = "*", 
        `access-control-allow-methods` = "GET, PUT, POST, DELETE, PATCH, OPTIONS", 
        `access-control-allow-headers` = "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization", 
        `x-uniprot-release-date` = "10-June-2026"), class = "httr2_headers"), 
    body = charToRaw("{\"jobId\":\"y4GfokxbBt\"}"), timing = c(redirect = 0, 
    namelookup = 0.002263, connect = 0.021015, pretransfer = 0.058147, 
    starttransfer = 0.088333, total = 0.088441), cache = new.env(parent = emptyenv())), class = "httr2_response")
