#' Extract the cRAP protein accessions from a fasta file
#'
#' @description A standard theme to use for plots generated by this package.
#'
#' @param base_size `numeric`. Defines the overall size of the plot.
#' @param base_family `string`. Fontfamily to use, default is `"sans"`.
#' @param base_line_size `numeric`. Defines the line size to use.
#' @param base_rect_size `numeric`. Defines the rect size to use.
#' @param aspect_square `logical`. Should a square aspect ratio be used?
#' Default is `TRUE`.
#' @param border `logical`. Should the plot have a square border?
#' Default is `TRUE`.
#'
#' @return Returns a _theme_ object.
#' @export
#'
#' @examples
#' set.seed(11)
#' library(ggplot2)
#'
#' df <- diamonds[sample(nrow(diamonds), 1000), ]
#'
#' ggplot(df, aes(x = price, y = carat)) +
#'   geom_point() +
#'   theme_biomasslmb()
#'
get_crap_fasta_accessions <- function(infile){
  # Load the cRAP FASTA used for the PD search
  crap.fasta <- Biostrings::fasta.index(infile, seqtype = "AA")

  # Define a base R version of stringr::str_extract_all()
  # base R str_extract
  str_extract_all <- function(pattern, string) {
    gregexpr(pattern, string, perl = TRUE) %>%
      regmatches(string, .) %>%
      unlist()
  }

  # Extract the non cRAP UniProt accessions associated with each cRAP protein
  crap.accessions <- crap.fasta %>%
    pull(desc) %>%
    str_extract_all("(?<=\\|).*?(?=\\|)", .) %>%
    unlist()

  return(crap.accessions)
}


